version: "3"
services:
    nodejs-app:
        image: fortune_ode_app
        ports:
            - "3000:3000"
        depends_on:
            - mongodb
        environment:
            - MONGO_URL= mongodb://mongodb:27017/my-db
    mongodb:
        image: mongo
        container_name: my-mongodb
        ports:
            - "27017:27017"
